### ISSUE TITLE
Is there a way to use this with multicontrolnet in A1111

### ISSUE THREAD

**Issue by ghpkishore** [AIGText/GlyphControl-release#2]
i wanted to know if there is a way for us to use your controlnet model over SD v1.5 or similar architecture based models and add glyph controlnet on top of that. (similar to how multicontrolnet is being used right now). Please let us know if it is possible or not, and if so , how can one go about implementing it?

Thanks

**Comment by PkuRainBow** [comment]
@yukang123 @guidongnan Please help to answer the question.

**Comment by yukang123** [comment]
Hi @ghpkishore, thanks for your questions!

Since our GlyphControl framework is mainly based on the ControlNet. It is possible to transfer our controlnet model onto other stable diffusion models. To do so, it is necessary to extract the model parameters of ControlNet part (i.e., glyph controlnet in our scenario) from the released checkpoints as the ControlNet v1.1 does.  Then you could use these parameters as one type of control to use onto other SD models. 

Although it is doable, I could not gaurantee the outcomes. Since our model was trained based on SD v2.0, it may bring differences while using other SD models.  Besides, the effects of combining our glyph controlnet with other controlnet models using canny maps or segmentation maps, are still worth exploring.

**Comment by ghpkishore** [comment]
Hi @yukang123 

Thanks for your response. Appreciate it. You mentioned it is possible to get the extract the controlnet part of the model out. Can you help me with the script which I need to use for it to work. Also I saw from the checkpoints on HF that they are roughly 6.67 GB and wanted to know how big would be the extracted controlnet. 

I agree that it is trained on V2 and hence might not work well with other models, but I am willing to try. 

My goal is to get a .pth file similar to controlnet v1.1 models ([https://huggingface.co/lllyasviel/ControlNet-v1-1/tree/main](https://huggingface.co/lllyasviel/ControlNet-v1-1/tree/main)) so that I can directly run it with the existing controlnet webui from A1111. This is the note from the controlnet repo owner for using custom models:

> Note: If you download models elsewhere, please make sure that yaml file names and model files names are same. Please manually rename all yaml files if you download from other sources. (Some models like "shuffle" needs the yaml file so that we know the outputs of ControlNet should pass a global average pooling before injecting to SD U-Nets.)

Request you to let me know how to proceed. Thanks

**Comment by yukang123** [comment]
The basic way is to load the entire the model and only save the parts related to the controlnet part. You could get referrence about how to load the model from the inference.py and cldm/cldm.py, and try to save the model parameters related to ControlNet (probably self.control_model in the cldm.py). 

The whole procedure is simple to implement. You could try to extract the parameters and compare with the released controlnet v1.1 models.

**Comment by ghpkishore** [comment]
@yukang123 thanks. There is this script: https://github.com/Mikubill/sd-webui-controlnet/blob/main/extract_controlnet.py

Would this be able to extract the controlnet. If you think there is a possibility, then I will do so. Thanks

**Comment by yukang123** [comment]
I think it would be very helpful for extraction. But I still suggest that you should read the codes first in case of some errors during extractions. 

In general, the script you mentioned should be fine.
